[profile.default]
solc = "0.8.13"
optimizer_runs = 1000000
bytecode_hash = "none"
no_match_test = "FFI|LongRunning"
verbosity = 4 
gas_reports = ["*"]

[profile.intense]
no_match_test = "FFI"

[profile.intense.fuzz]
runs = 10000

[profile.ffi]
ffi = true
no_match_test = "LongRunning"

src = 'src'
out = 'out'
libs = ['lib']

[profile.gas_reports]


[profile.ci]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config